### ISSUE TITLE
(manager) language not working

### ISSUE THREAD

**Issue by janniconl** [yama/tinymce4-for-modx-evo#4]
Seems like the 'language' variable is not set in tinymce.init

See: https://www.tinymce.com/docs/configure/localization/#language

Current result:
````
[...]
language_url:'/modx11/assets/plugins/tinymce4/tinymce/langs/nl.js',
````

Expected result:
````
[...]
language_url:'/modx11/assets/plugins/tinymce4/tinymce/langs/nl.js',
language:'nl',
````

Tested by adding `$cfg['language'] = "{$lang_code}";` to rule 85 in `plugin.class.inc.php`, which adds the language variable. 

However I see also your function `build_mce_init`, which has:
`$ph['language'] = (empty($params['language'])) ? 'en' : $params['language'];` 
This does nothing for me though. (sorry my php is not that good)

Using latest development version of modx 1.1 and the latest tinymce4 from this repo.

**Comment by Deesen** [comment]
As the description states the fork has moved. So you can find latest version here https://github.com/extras-evolution/tinymce4-for-modx-evo

**Comment by janniconl** [comment]
Oh sorry missed that, will repost there :)
